# Generated by Django 3.1.5 on 2021-03-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210307_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='profile',
        ),
    ]
