# Generated by Django 3.1.5 on 2021-03-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_profile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wallet',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
