# Generated by Django 3.1.5 on 2021-03-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_paymentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdata',
            old_name='password',
            new_name='payment_password',
        ),
    ]
