# Generated by Django 3.1.5 on 2021-03-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20210309_1213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paymentdata',
        ),
    ]
