# Generated by Django 3.1.5 on 2021-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_paymentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_password',
            field=models.CharField(blank=True, default='hello', max_length=25, null=True),
        ),
    ]
