# Generated by Django 3.1.5 on 2021-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_profile_payment_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='payment_password',
            field=models.CharField(blank=True, default='hello', max_length=255, null=True),
        ),
    ]
